<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Lanshu.Presenter.Cli</RootNamespace>
    <AssemblyName>lanshu</AssemblyName>
    <RollForward>Major</RollForward>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <AssemblyTitle>Lanshu Presenter CLI</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lanshu.Presenter.Core\Lanshu.Presenter.Core.csproj" />
  </ItemGroup>

</Project>
